project:
  type: website

website:
  title: "Ben Brintz"
  navbar:
    background-color: "#383838"  # A dark muted gray that will let the artwork shine
    font:
      family: "Arial, sans-serif"  # A neutral font that will be easy to read against the dark background
      color: "#F0F0F0"  # A light gray for good contrast against the dark navbar
      size: "16px"
      hover-color: "#DAA520" 
    left:
      - href: index.qmd
        text: Home
      - href: https://scholar.google.com/citations?user=nYA8PAsAAAAJ&hl=en
        text: Publications
      - href: sierpinski.qmd
        text: Sierpinski Triangle
      - href: mmdis/mmdis.qmd
        text: Presentations
        
 # A golden color, inspired by some tones in the image

format:
  html:
    theme: "sandstone"
    toc: false
    css: 
      - custom-layout.css
    

    
execute:
  freeze: auto

  #quarto render --to all